library(dplyr)
library(lubridate)
library(tidyr)
library(data.table)
library(shiny)
library(tidyverse)
library(shinyWidgets)
library(xts)
library(dygraphs)
library(flextable)
library(officer)
library(gtable)
library(knitr)
library(kableExtra)
library(shinydashboard)
library(yaml)
library(shinycssloaders)
library(plotly)
library(DBI)
library(pool)
library(dbConnect)
 library(scales)
library(dbConnect)
library(jsonlite)
library(mongolite)
library(shinydashboard)
# 
# 
businesspartner = mongo(verbose = T,url = "mongodb://127.0.0.1:27017",db = "springbatch",collection = "BusinessPartnerinfo")
salesinfo= mongo(verbose = T,url = "mongodb://127.0.0.1:27017",db = "springbatch",collection ="salesorderinfo")
salesline= mongo(verbose = T,url = "mongodb://127.0.0.1:27017",db = "springbatch",collection = "salesorderlineinfo")
ofc = read.csv(file = "/home/uttam/Ofc/dash1/ofc.csv")